name: S&P 100 Live Radar

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * 1-5"

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: pip install yfinance pandas
      - name: Run Cycles
        run: |
          # Borrar el progreso solo UNA VEZ al inicio del flujo
          rm -f progreso.json
          
          for i in {1..10}
          do
            echo "Iniciando ciclo $i..."
            python agente.py
            
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add index.html progreso.json
            git commit -m "update cycle $i" || echo "no changes"
            git push --force origin HEAD:main
            
            echo "Esperando 120 segundos para evitar bloqueos..."
            sleep 120
          done
